### ISSUE TITLE
Editing broken with plugin activated

### ISSUE THREAD

**Issue by plamenh** [spacedmonkey/wp-rest-blocks#13]
Blank (white) page on post edit.

Wordpress 5.7.2

**Comment by spacedmonkey** [comment]
@plamenh  How did you install the plugin? Did you run composer install? 

Can you download a built version of the plugin [here](https://github.com/spacedmonkey/wp-rest-blocks/releases/download/0.2.0/wp-rest-blocks.zip).

**Comment by simonknittel** [comment]
@plamenh Do you use Yoast? We've noticed, that adding blocks to the REST API results in a blank page as long as Yoast is enabled.

We first tried adding blocks to the API via a simple custom plugin and then tried this plugin. It didn't make any difference.

We boilt it down to the return value of the `get_callback` function. Just returning an empty array works. Returning the result of `parse_blocks` doesn't work.

```php
register_rest_field($post_type, 'blocks', [
  'get_callback' => function(array $post) {
    $array = parse_blocks($post['content']['raw']);

    return $array; // Doesn't work
    // return array(); // Works
  }
]);
```

**Comment by plamenh** [comment]
As a matter of fact, yes, we do use yoast. I guess we will just disable it, seems like the most straightforward fix. Thanks.

**Comment by spacedmonkey** [comment]
@simonknittel So the issue is related to yoast being installed?

**Comment by simonknittel** [comment]
> @simonknittel So the issue is related to yoast being installed?

I guess so. Two workarounds I found:
1. Disable Yoast
2. Use some other property name than `blocks`

**Comment by spacedmonkey** [comment]
I believe that https://github.com/spacedmonkey/wp-rest-blocks/pull/18 might this fix. Watch this space.

**Comment by spacedmonkey** [comment]
@plamenh @simonknittel Can you install version 0.3.0 and see if this is still an issue?

**Comment by plamenh** [comment]
@spacedmonkey I can confirm 0.3.1 works fine with Yoast SEO turned on. Thanks.

**Comment by CHEWX** [comment]
Yep I had issue with Yoast too, but when both plugins are up to date, all is fine.
