### ISSUE TITLE
Add to Wordpress.org/wpackagist.org

### ISSUE THREAD

**Issue by certainlyakey** [spacedmonkey/wp-rest-blocks#17]
Please add the package to Wordpress.org/wpackagist.org. Right now it's a PITA to deal with Github API limitations when installing/updating from composer.

**Comment by spacedmonkey** [comment]
Yes, I asked this question on twitter. https://twitter.com/thespacedmonkey/status/1412368314186317836?s=21

It is on my list to get around too. Watch this space.

**Comment by certainlyakey** [comment]
Thanks! 😊

**Comment by spacedmonkey** [comment]
Submitted to plugin repo.

**Comment by spacedmonkey** [comment]
@certainlyakey The plugin is now the WP.org repo. https://wordpress.org/plugins/rest-api-blocks/
